### ISSUE TITLE
Semi performance, handling of [] <.>

### ISSUE THREAD

**Issue by jrp2014** [conal/convolution-paper#1]
Thanks for putting this up, Conal.  This is the kind of Haskell magic that one dreams about: get the types right (in this case, feed in the right types) and something sensible comes out.

A couple of small observations after a bit of a play:

- that `<.>` is the convolution operator that is at the core of the package, it doesn't seem to reject empty lists. 
```
*Semi> [] <.> []
[]
*Semi> [] <.> [1,2]
[]
*Semi> [1,2] <.> []
[0,0]
*Semi> 
```

- While the maths / implementation are elegant, the performance is not yet optimised:

```
convolve' :: (Num a) => [a] -> [a] -> [a]
convolve' hs xs =
  let pad = replicate (length hs - 1) 0
      ts  = pad ++ xs
  in  map (sum' . zipWith (*) (reverse hs)) (init $ tails ts)

sum' :: (Foldable t, Num a) => t a -> a
sum' = foldl' (+) 0
```
runs quite a bit faster.  Not sure why.  (This also blows up if you feed it an empty list.)

BTW, the repo will work with GHC 8.6.5 by pointing to the latest resolver, which is gratifying.

**Comment by conal** [comment]
Thanks for the comments.

Would you expect  convolution to reject empty lists, and if so, why?

Does anything surprise you about the convolution examples you tried above?

I'm not concerned about efficiency on `[]` for convolution or just about anything, in part because efficiency these days comes from massive parallelism, and lists are intrinsically sequential.

**Comment by jrp2014** [comment]
Conal, I would not expect it do be defined for empty lists.  As you can see, the empty cases are not commutative, which is also unhelpful.

I take your efficiency point, although we are comparing lists with lists here, and applying a very naive parallel wrapper to the list gives a further significant speedup.  I haven't tried to do the same with your operators.
```
parConvolve :: (NFData a, Num a) => [a] -> [a] -> [a]
parConvolve [] _ = []
parConvolve hs xs =
  let pad = replicate (length hs - 1) 0
      ts  = pad ++ xs
  in  parMap rdeepseq (sum' . zipWith (*) (reverse hs)) (init $ tails ts)
```

**Comment by conal** [comment]
Why would you expect `(<.>)` not to be defined on empty lists?

I think the lack of commutativity here is compatible with the specification of `(<.>)` in general and for lists specifically. (It would also be compatible to drop trailing zeros.) From page 20 of the paper, "define instances directly for lists, specified by a denotation of `[b]` as `N -> b`." As always, the rest of the specification is that the denotation is a homomorphism. I'm happy to expand if this explanation unclear.

**Comment by jrp2014** [comment]
Perhaps I am thinking too much about applications, where an empty arg to a convolution doesn't make much sense. I do, however, think, for a piece of code that has convolution in the title, the convolution operator should satisfy the normal laws, or explain, where it doesn't.  (I don't want to make heavy weather of this; I like the fact that your abstraction gives convolution almost as a by-product; the performance is also a bit moot as one would use an FFT where that was critical, although it would be great if it was possible to parallelise the Semi machinery under the hood.

**Comment by conal** [comment]
> Perhaps I am thinking too much about applications, where an empty arg to a convolution doesn't make much sense.

I don't know what you mean by an "empty arg". Note that convolution fundamentally is defined on *functions*, and that its meaning on lists is specified via the denotation of lists as functions on the natural numbers, as mentioned in my previous comment. In particular, the empty list denotes the constant zero function, which I suspect you'd agree does make perfect sense. In this sense, if the element semiring has commutative multiplication, then `(<.>)` is indeed commutative, where equality is denotational. In your example, `[]` and `[0,0]` are denotationally equal in that they both denote the constant zero function.

Did you have a different interpretation (or application) of lists in mind for which convolution is not well-defined on empty lists?

> it would be great if it was possible to parallelise the Semi machinery under the hood.

Yes, absolutely. Since I care about performance, I intend to target massively parallel hardware, not CPUs (even multi-core), probably via compiling-to-categories.

**Comment by jrp2014** [comment]
Thanks, Conal.  That's a clear explanation.

**Comment by conal** [comment]
My pleasure. Thanks for the conversation!
